# cloudbuild.yaml - build & push images (simple: only :latest)
substitutions:
  _REPO_LOCATION: "us-central1"
  _REPO_NAME: "skillbridge-repo"

steps:
# users-service
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/users-service:latest', './users-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/users-service:latest']

# availability-service
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/availability-service:latest', './availability-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/availability-service:latest']

# booking-service
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/booking-service:latest', './booking-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/booking-service:latest']

# messaging-service
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/messaging-service:latest', './messaging-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/messaging-service:latest']

# code-review-service
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/code-review-service:latest', './code-review-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/code-review-service:latest']

# frontend
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/frontend:latest', './users-service-frontend/sb-web']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REPO_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/frontend:latest']

# final print
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Pushed:"
      echo "us-central1-docker.pkg.dev/$PROJECT_ID/skillbridge-repo/{users-service,availability-service,booking-service,messaging-service,code-review-service,frontend}:latest"

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/skillbridge-repo/users-service:latest'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/skillbridge-repo/availability-service:latest'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/skillbridge-repo/booking-service:latest'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/skillbridge-repo/messaging-service:latest'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/skillbridge-repo/code-review-service:latest'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/skillbridge-repo/frontend:latest'
