# k8s/availability.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: availability-db-secret
  namespace: skillbridge
stringData:
  POSTGRES_PASSWORD: "postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: availability-config
  namespace: skillbridge
data:
  PORT: "4102"
  DATABASE_URL: "postgresql://postgres:postgres@availability-db:5432/availability_db?schema=public"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: availability-db
  namespace: skillbridge
spec:
  serviceName: "availability-db"
  replicas: 1
  selector:
    matchLabels:
      app: availability-db
  template:
    metadata:
      labels:
        app: availability-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: availability-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "availability_db"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: availability-db
  namespace: skillbridge
spec:
  selector:
    app: availability-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: availability-deployment
  namespace: skillbridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: availability
  template:
    metadata:
      labels:
        app: availability
    spec:
      containers:
      - name: availability
        image: us-central1-docker.pkg.dev/skillbridge-demo/skillbridge-repo/availability-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4102
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: availability-config
              key: PORT
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: availability-config
              key: DATABASE_URL
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 4102
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4102
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: availability-service
  namespace: skillbridge
spec:
  selector:
    app: availability
  ports:
    - protocol: TCP
      port: 4102
      targetPort: 4102
  type: ClusterIP
---
apiVersion: batch/v1
kind: Job
metadata:
  name: availability-migrate
  namespace: skillbridge
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: us-central1-docker.pkg.dev/skillbridge-demo/skillbridge-repo/availability-service:latest
        command: ["sh", "-c", "npx prisma migrate deploy"]
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: availability-config
              key: DATABASE_URL
      restartPolicy: OnFailure
  backoffLimit: 1
